/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package boxsniffer;

import java.awt.GridLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.ListModel;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.event.AncestorEvent;
import javax.swing.event.AncestorListener;

/**
 *
 * @author willdech
 */
public class LinkGUI extends javax.swing.JFrame {
    
    private final BoxSniffer ls = new BoxSniffer();
    private List allCourses = new ArrayList();
    private ListModel listModel;
    private int selected = 0;
    Thread audit = null;
    Thread prog = null;
    
    /**
     * Creates new form LinkGUI
     */
    public LinkGUI() {
        initComponents();
    }
    
    public boolean loginPopup(){
        final JTextField username = new JTextField();
        JTextField password = new JPasswordField();
        JTextField prefix = new JTextField();
        JPanel gridLayout = new JPanel(new GridLayout(6, 1));
        gridLayout.add(new JLabel("Username:"));
        gridLayout.add(username);
        gridLayout.add(new JLabel("Password:"));
        gridLayout.add(password);
        gridLayout.add(new JLabel("Prefix:"));
        gridLayout.add(prefix);

        username.addAncestorListener(new AncestorListener() {
            @Override
            public void ancestorRemoved(AncestorEvent pEvent) {
            }

            @Override
            public void ancestorMoved(AncestorEvent pEvent) {
            }

            @Override
            public void ancestorAdded(AncestorEvent pEvent) {
                username.requestFocusInWindow();
            }
        });

        int option = JOptionPane.showConfirmDialog(null, gridLayout, "Login",
            JOptionPane.OK_CANCEL_OPTION);
        if (option == JOptionPane.OK_OPTION) {
            return ls.login(username.getText(), password.getText(), prefix.getText());
        } else {
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginBtn = new javax.swing.JButton();
        domainid = new javax.swing.JTextField();
        domainBtn = new javax.swing.JButton();
        pickScroll = new javax.swing.JScrollPane();
        pickCourse = new javax.swing.JList();
        auditBtn = new javax.swing.JButton();
        sniffProgress = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pause = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        queryTxt = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Brainhoney HTML Sniffer");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        loginBtn.setText("Login");
        loginBtn.setToolTipText("Login to Agilix");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        domainid.setText("2522027");
        domainid.setToolTipText("");
        domainid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                domainidActionPerformed(evt);
            }
        });

        domainBtn.setText("List Courses");
        domainBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                domainBtnActionPerformed(evt);
            }
        });

        pickCourse.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Select a course" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        pickCourse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pickCourseKeyPressed(evt);
            }
        });
        pickScroll.setViewportView(pickCourse);

        auditBtn.setText("Start");
        auditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                auditBtnActionPerformed(evt);
            }
        });

        sniffProgress.setBackground(new java.awt.Color(204, 204, 204));

        displayArea.setColumns(20);
        displayArea.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        displayArea.setRows(5);
        displayArea.setEnabled(false);
        jScrollPane1.setViewportView(displayArea);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Audit Area");

        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchKeyTyped(evt);
            }
        });

        jLabel3.setText("Domain Id: ");

        jLabel4.setText("Search:");

        pause.setText("Pause");
        pause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseActionPerformed(evt);
            }
        });

        jLabel5.setText("Query");

        queryTxt.setText("[href*=.box.]:not([href*=embed]):not([href*=static]),[src*=.box.]:not([src*=embed]:not([src*=static])),[value*=.box.]:not([value*=embed]):not([value*=static])");
        queryTxt.setToolTipText("");

        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(172, 172, 172)));

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setFont(new java.awt.Font("Gulim", 0, 12)); // NOI18N
        jMenuItem1.setText("Login");
        jMenuItem1.setToolTipText("Login to Agilix");
        jMenuItem1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Get");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setText("Exit");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("View");

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setText("Error Log");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Tools");

        jMenuItem7.setText("CSS Sniffer Test");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem7);

        jMenuBar1.add(jMenu4);

        jMenu2.setText("Help");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setFont(new java.awt.Font("Gulim", 0, 12)); // NOI18N
        jMenuItem2.setText("About");
        jMenuItem2.setToolTipText("About this product");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem4.setText("Shorcuts");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(auditBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pause)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sniffProgress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(pickScroll)
                    .addComponent(queryTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(domainid, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(loginBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(domainBtn))
                        .addComponent(jLabel5))
                    .addComponent(search, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(domainid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(domainBtn)
                            .addComponent(loginBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(queryTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pickScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(auditBtn)
                                .addComponent(pause))
                            .addComponent(sniffProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        if (!loginPopup()){
            this.displayArea.setText("Login Failure");
            this.displayArea.setText(ls.displayErrorMsgs());
        }
        else{
            this.domainid.setEnabled(true);
            this.auditBtn.setEnabled(true);
            this.domainid.requestFocus();
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    public void domainBtn(){
        Thread get = new Thread(){
            @Override
            public void run() {
                if (ls.getDomainCourses(domainid.getText())){
                    allCourses = ls.getAllCourses();
                    displayArea.setText("");
                    addToList("");
                    repaint();
                    search.requestFocus();
                }
                else{
                    displayArea.setText("Invalid Domain Id");
                }
            }  
        };
        get.start();
        displayArea.setText("Getting Courses...");
    }
    
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        if (!loginPopup()){
            this.displayArea.setText("Login Failure");
            this.displayArea.setText(ls.displayErrorMsgs());
        }
        else{
            this.domainid.setEnabled(true);
            this.auditBtn.setEnabled(true);
            this.domainid.requestFocus();
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void domainBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_domainBtnActionPerformed
        // TODO add your handling code here:
        domainBtn();     
    }//GEN-LAST:event_domainBtnActionPerformed

    public void startProcess(){
        this.ls.reset();
        final String courseid = this.pickCourse.getSelectedValue().toString().split("::")[1];
        audit = new Thread(){
            @Override
            public void run() {
                ls.dlapGetItemList(courseid);
                String query = queryTxt.getText();
                ls.run(query);
                showBroken(ls.displayBrokenLinks());
                this.interrupt();
                auditBtn.setEnabled(true);
                displayArea.setEnabled(true);
            }  
        };  
        prog = new Thread(){
            @Override
            public void run() {
                while(audit.isAlive()){
                    if (ls.isRunning()){
                        setProgress();
                        displayArea.setText(ls.displayBrokenLinks());
                    }
                }
            }  
        };
        this.auditBtn.setEnabled(false);
        audit.start();
        audit.setName("Link Sniffer");
        prog.start();
        prog.setName("Link Sniffer");
        displayArea.setText("Auditing course, please wait...\n\nWhile you wait, you can count how many times you blink.");
    }
    
    private void auditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_auditBtnActionPerformed
        // TODO add your handling code here:
        startProcess();
    }//GEN-LAST:event_auditBtnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.domainid.setEnabled(false);
        this.auditBtn.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    private void domainidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_domainidActionPerformed
        // TODO add your handling code here:
        domainBtn();
    }//GEN-LAST:event_domainidActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_searchActionPerformed

    private void searchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyTyped
        // TODO add your handling code here:
        addToList(this.search.getText());
        this.selected = 0;
    }//GEN-LAST:event_searchKeyTyped

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Created by: Chase Willden"
                + "\nFor Professional Use Only."
                + "\nTechnologies used:"
                + "\n   JSoup - HTML parser");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        domainBtn();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 40 || evt.getKeyCode() == 38){
            this.pickCourse.setSelectedIndex(0);
            this.pickCourse.requestFocus();
        }
    }//GEN-LAST:event_searchKeyPressed

    private void pickCourseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pickCourseKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 40){
            this.pickCourse.setSelectedIndex(this.selected++);
            
        }
        if (evt.getKeyCode() == 38){
            this.pickCourse.setSelectedIndex(this.selected--);
        }
        if (evt.getKeyCode() == 10){
            startProcess();
        }
    }//GEN-LAST:event_pickCourseKeyPressed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        String text = "=== Available Shortcuts ===\n";
        text += "\nCtrl+L    - Login";
        text += "\nCtrl+G    - Get Courses from Domain Id";
        text += "\nDown      - Go down through courses list";
        text += "\nUp      - Go up through courses list";
        this.displayArea.setText(text);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        System.exit(-1);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void pauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseActionPerformed
        // TODO add your handling code here:
        if (this.pause.getText().contains("Pause")){
            this.pause.setText("Resume");
            ls.setInterrupt(true);
        }
        else{
            this.pause.setText("Pause");
            ls.setInterrupt(false);
        }
    }//GEN-LAST:event_pauseActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        this.displayArea.setText(ls.displayErrorMsgs());
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new boxsniffer.Tools.OspreyGUI().setVisible(true);
            }
        });
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    public void showBroken(String brokens){
        
        this.displayArea.setText(brokens);
    }
    
    public void setProgress(){
        if (ls.progress() > 1){
            int progress = (int) ls.progress();
            this.sniffProgress.setValue(progress);
        }
        
    }
    
    public void addToList(String filter){
        final String[] strings = new String[this.allCourses.size()];
        int next = 0;
        for (int i = 0; i < this.allCourses.size(); i++){
            if (filter.isEmpty()){
                strings[next++] = this.allCourses.get(i).toString();
            }
            else{
                if (this.allCourses.get(i).toString().toLowerCase().indexOf(filter.toLowerCase()) != -1){
                    strings[next++] = this.allCourses.get(i).toString();
                }                
            }
        }
        pickCourse.setModel(new javax.swing.AbstractListModel() {
            @Override
            public int getSize() { return strings.length; }
            @Override
            public Object getElementAt(int i) { return strings[i]; }
        });
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            LookAndFeelInfo[] feels = UIManager.getInstalledLookAndFeels();
            for (LookAndFeelInfo feel : feels){
                String name = feel.getName();
                if (name.equals("Windows")){
                    UIManager.setLookAndFeel(feel.getClassName());
                }
                else{
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LinkGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new LinkGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton auditBtn;
    private javax.swing.JTextArea displayArea;
    private javax.swing.JButton domainBtn;
    private javax.swing.JTextField domainid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loginBtn;
    private javax.swing.JButton pause;
    private javax.swing.JList pickCourse;
    private javax.swing.JScrollPane pickScroll;
    private javax.swing.JTextField queryTxt;
    private javax.swing.JTextField search;
    private javax.swing.JProgressBar sniffProgress;
    // End of variables declaration//GEN-END:variables
}
